install:
	npm ci

start:
	npm run start

build-dev:
	rm -rf build
	npm run build-dev

build-prod:
	rm -rf build
	npm run build-prod

build-analyzer:
	rm -rf build
	npm run build-analyzer
